CREATE TABLE beer_diary_beers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    beer_id TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    brewery TEXT NOT NULL,
    image TEXT NOT NULL,
    abv TEXT,
    ibu TEXT,
    beer_style TEXT,
    description TEXT
);