CREATE TABLE beer_diary_reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES beer_diary_users(id) ON DELETE CASCADE NOT NULL,
    beer_id TEXT
        REFERENCES beer_diary_beers(beer_id) ON DELETE CASCADE NOT NULL,
    overall INTEGER NOT NULL,
    color INTEGER NOT NULL,
    drinkability INTEGER NOT NULL,
    notes TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);